### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by JeffersonAero** [RMDLO/COCOpen-OpenCV#20]
- [x] The initial copy should be really short and punchy to grab people’s attention before they lose interest and move on. You should be able to explain most of what it does using example images, which I think will get the point across really rapidly.
- [x] We need getting started and installation instructions sections (for example, see the detectron2 README.md)
- [x] We have nonstandard stuff in repository; to extent possible, organize the README.md in the same manner as some of the other open source libraries that we respect and are widely used
- [x] You should describe what environment the installation instructions are expecting to run in.
- [x] The install instructions should finish with “how to run it” instructions that are a concrete example of actually running it with a data set that’s available to the novice user, so everything works end-to-end out of the box and they can try tweaking it from there. It looks like your current run.py script needs to be run with your personal Azure environment configured so it can access the images, so that won’t work for an arbitrary user (right?). Is there some way you can expose your data to them using a read-only globally accessible URL so it will work?
- [x] "Running API" - not immediately clear that we provide instructions on how to use the library
- [x] Need to provide assumptions that are made about the set of images, maybe other stuff that has to be provided
- [ ] Provide the smallest, simplest version of that stuff included also made publicly available (as part of repo), so someone could clone repo and follow instructions to get it to generate a labeled dataset from small, simple example. this would be a very small but complete example of all stuff that must be input to library that allows user to get started with generating the set of images (the hello-world run-it instructions should probably do something quick and make it easy for users to inspect the results, not regenerate the whole UIUC Wires data set). It would be a weird limiter to make this really depend on Azure in any way - maybe include a small set of simple example images in the repository.
- [x] Not getting much from the figure at the moment
- [x] Some part of the repository should include instructions on how to collect your own input images and create your own data set.
- [x] Getting started+Run instructions should correspond to diagram in README.md. The proposed solution describes what happens when run the API, so it would be nice if all of these were combined
- [x] Don't set apart the note in the anaconda environment. Either: (a) assume people know how to create a conda environment in README.md (minimize the stuff that you say) and simplify installation instructions, OR (b) Provide very detailed step-by-step instructions (e.g., https://tbretl.github.io/ae353-sp22/setup). Providing too many instructions is probably overkill for our repo.

**Comment by JeffersonAero** [comment]
Should the [azure](https://github.com/RMDLO/COCOpen-OpenCV/blob/main/README_AZURE.md) instructions be moved to a separate `docs/` folder?

**Comment by JeffersonAero** [comment]
- [ ] EXAMPLE_RUN.md: RE: the line “run_demo: True”. True != true. Maybe YAML treats them the same but probably better to be consistent with other flags.
- [ ] EXAMPLE_RUN.md: “User defined parameters”. Users can configure all of the parameters, so that’s not very descriptive. Better would be “Pointer to raw input imagery”
- [ ] EXAMPLE_RUN.md: Some of the code blocks are calling for “bash” syntax highlighting when it should be “yaml”.
- [ ] EXAMPLE_RUN.md: In the code block running “bash run.sh”: This line is a bit confusing because it has an elaborate prompt string that people might interpret as part of the command. Maybe remove the prompt string altogether? (Also makes it easier to copy/paste into terminal for lazy reader.) Also, I would typically write this “./run.sh” instead of “bash run.sh”, except that won’t actually work because the “run.sh” script is missing the standard “#!/bin/sh” initial line (and is it executable?). What you are doing is already technically correct, but I think most folks would expect “./run.sh” to work.
- [ ] EXAMPLE_RUN.md: It’s a bit mysterious what “perform the demo” might mean. Is it mentioned anywhere? (This is especially important to explain when you’re hoping to attract lots of external users. A good bug report compares “expected behavior” to “observed behavior”, which is hard when your users don’t know what to expect.)
- [ ] Front page: The second image with the black-and-white masks is kind of incomprehensible. Remove it.
- [ ] Front page: The first image would make more sense with a caption. Like “COCOpen-produced synthetic image containing multiple objects of interest superimposed on a randomly selected background, with ground truth labels.”
- [ ] Maybe it’s too much of a pain, but I think it could be possible to do an improved version of your block flow diagram where each block is replaced by one or more illustrative example images at that step in the processing. Among other things, that would give users more immediate insight about what kind of input data COCOpen is using.
- [ ] EXAMPLE_RUN.md / GETTING_STARTED.md: I think these can be consolidated? I like EXAMPLE_RUN.md better. A good pattern is to have a “quick startup” step-by-step guide a la EXAMPLE_RUN, with only brief explanations of what the steps are doing, followed by more expansive reference-like discussion of any advanced features.
- [ ] Do not hide the “docs” folder under “.github”. I think of “.github” as the place for configuration that’s specific to having the code hosted on GitHub, like the CI workflows. If you put files there, they could easily be overlooked by folks who checked out the code instead of browsing in the GitHub interface.
- [ ] Is it possible to browse your raw input imagery in cloud storage? If yes, I think a pointer to that browsing interface from the docs would provide useful insight.
- [ ] The config file is a big improvement! My instinct though is that the canonical config file for a data set should be stored in a standard location within that data set. That would simplify people providing new COCOpen input data sets with the config batteries included. One possible approach could be to split the current config file into two pieces: (1) data set location, (2) other config parameters. Then, when working with somebody else’s data set, you can either specify only (1) and it will look for their standard config (2) within their data set, or you can specify both (1) and (2) so that your config overrides their standard config.

**Comment by yrraadi-io** [comment]
The splash page (https://rmdlo.github.io/COCOpen-OpenCV/):

- [ ] Should have a link to the repository (e.g., "get the code" or something).
- [ ] (Intro) You say "this repository uses the UIUC COCOpen Library." What does "this repository" refer to? I am confused because the first word of the paragraph implies that you are describing the UIUC COCOpen Library on this splash page, but I think — I could be wrong — you are describing something else ("this repository," which may be called "COCOpen-OpenCV") that has the UIUC COCOpen Library as a dependency. One solution to this problem would be to start the intro paragraph by naming the thing you are actually describing, rather than the dependency. This is another good example of "don't bury the lede."
- [ ] You may want to make clear — e.g., in the intro paragraph — what must be provided to your method in order for it to generate a labelled dataset. You can't just give it any old set of images, right?

The installation page (https://github.com/RMDLO/COCOpen-OpenCV/blob/main/docs/INSTALLATION.md):

- [ ] "This notebook contains..." — it's not a notebook.
- [ ] "Environment information" — normally, I would expect to see something like "System requirements." This section might then say what systems you personally used for testing, and might say that you expect it to work on systems Y and Z as well but that these haven't been tested. Something like that. I would not mention the environment.yaml file yet, since that's a conda thing.
- [ ] When giving commands to execute in a terminal, please don't include the prompt — I believe that's a dollar sign $ on this page (which is dangerous, because that symbol has a special meaning in bash). If you include the prompt, then it's that much harder to copy/paste the commands. Also, I would only put commands in the same code box when it is ok — even recommended — to copy/paste all of them into a terminal at the same time, rather than copy/paste commands one at a time. I appreciate your use of comments.
- [ ] I would normally refer only to "conda" and "conda environments" rather than to anaconda. I normally think of "anaconda" and "miniconda" as being two different ways of getting "conda" for instance.
- [ ] "Clone this repository..." — I would minimize confusion (see my comments about the splash page) by always naming the repository you are talking about rather than referring to it as "this."
- [ ] I think it is customary to use the extension yml instead of yaml. (You seem to do this with train_environment.yml but then use environment.yaml.)
- [ ] Given that you have a train_environment file, I might call the other one dataset_environment or something rather than just environment.
- [ ] Be direct whenever possible — so, "Follow these instructions to configure your dataset on Azure" rather than "To learn how to set up your dataset on Azure, read our configuration instructions." (Note — I don't understand the difference between "set up your dataset" and "configure a new dataset.")
- [ ] I don't understand what it means to "Run the COCOpen Example" — I am confused about the difference between this "example" and the "example" to which the splash page refers (the "simple dataset" example).
- [ ] "An example annotation is visualized with the detectron2 visualizer below." is awkward ("visualized with the... visualizer"). How about something like: "Here is an example of an annotated image, as visualized with detectron2."

**Comment by JeffersonAero** [comment]
The example page (https://github.com/RMDLO/COCOpen-OpenCV/blob/main/docs/EXAMPLE_RUN.md):

- [ ] Section 2 has a typo: "a. The provided..."
- [ ] Section 3 (Adjust Parameters) — I assume the default values listed are the ones already in the config/parameters.yml file, so there isn't any need to show these values again here. Instead, what I really want to know is which parameters I need to change in order to run the demo. Perhaps I don't need to change any of them. In that case, this section should not tell me to "tweak parameters." Instead, this section might point out one or two important parameters that I could change (not "tweak") if I wanted to learn how they influence the results — parameters that I really would need to change if I were working with any other dataset.
- [ ] Section 4 (Running the script) — first, this should be "Run the script" so it is consistent with the other sections (similarly, Section 5 should be "Look at the result" or something instead of "Result"). Second, I don't think you've said what "the script" is yet, nor do you say what it is in this section — so the title of this section is a little confusing. Third, what does it mean "to execute the API?" You don't refer to "the API" anywhere else anymore, I don't think.
- [ ] You are still missing example annotations (I think you mean "examples of annotated images?") in Section 5.
- [ ] You might tell users how long each step is expected to take, or at least the "run the script" step — assuming this takes more than a few seconds.
- [ ] The "learn more" page (https://github.com/RMDLO/COCOpen-OpenCV/blob/main/docs/LEARN_MORE.md) is currently the weakest of all pages I have read. I like the (still-evolving) flow diagram, it's much better than what we looked at the other day (although it is hard to read — any way to make it auto-scale to the page width? or increase font size / contrast?). But I'm not getting much from the problem statement or proposed solution.

**Comment by yrraadi-io** [comment]
The example page (https://github.com/RMDLO/COCOpen-OpenCV/blob/main/docs/EXAMPLE_RUN.md):

- [ ] Section 2 has a typo: "a. The provided..."
- [ ] Section 3 (Adjust Parameters) — I assume the default values listed are the ones already in the config/parameters.yml file, so there isn't any need to show these values again here. Instead, what I really want to know is which parameters I need to change in order to run the demo. Perhaps I don't need to change any of them. In that case, this section should not tell me to "tweak parameters." Instead, this section might point out one or two important parameters that I could change (not "tweak") if I wanted to learn how they influence the results — parameters that I really would need to change if I were working with any other dataset.
- [ ] Section 4 (Running the script) — first, this should be "Run the script" so it is consistent with the other sections (similarly, Section 5 should be "Look at the result" or something instead of "Result"). Second, I don't think you've said what "the script" is yet, nor do you say what it is in this section — so the title of this section is a little confusing. Third, what does it mean "to execute the API?" You don't refer to "the API" anywhere else anymore, I don't think.
- [ ] You are still missing example annotations (I think you mean "examples of annotated images?") in Section 5.
- [ ] You might tell users how long each step is expected to take, or at least the "run the script" step — assuming this takes more than a few seconds.
